### ISSUE TITLE
Add playbin integration

### ISSUE THREAD

**Issue by hadess** [turran/gst-bt#3]
It would be useful for:
1) torrent files to be handled natively (without the need to manually insert btdemux)
2) installing a uri handler for magnet in btsrc (so it's auto-plugged)

The goal being that "gst-play-1.0 file.torrent" or "gst-play-1.0 magnet:..." both work out of the box.

This would allow me to enable torrent sources in Totem, in particular support for the Vodo grilo source:
https://github.com/grilofw/grilo-lua-sources/blob/master/grilo/grl-vodo.lua

**Comment by turran** [comment]
About 1:
Btdemux is autoplugged on the gst-play-1.0 case, even so I'm seeing some issues about no stream found, need to check, but the idea is that it should work.

About 2:
The btsrc does install the uri handler, just do

```
gst-play-1.0 "magnet:....."
```

check the bt\* log with GST_DEBUG=bt*:6 to see if it is actually working.

**Comment by turran** [comment]
Fixed on 821aed76e31243cfb5f00ede4f4f40a6394b85d0
